const COLOR_IMAGE_MAP = {
  "Airbrushed cats": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Airbrushed cats.jpg",
  "Alexandrite": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Alexandrite.jpg",
  "Alexandrite Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Alexandrite Iridized.jpg",
  "Alexandrite Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Alexandrite Satin.jpg",
  "Amber": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amber.jpg",
  "Amber Comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amber Comparison.jpg",
  "Amber Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amber Satin.jpg",
  "Amberina Crystal": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amberina Crystal.jpg",
  "Amberina Crystal Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amberina Crystal Satin.jpg",
  "Amethyst": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amethyst.jpg",
  "Amethyst Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amethyst Iridized.jpg",
  "Amethyst Plum Comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amethyst Plum Comparison.jpg",
  "Amethyst Plum Comparison2": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Amethyst Plum Comparison2.jpg",
  "Apple Green": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Apple Green.jpg",
  "Apple Green Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Apple Green Satin.jpg",
  "Aqua": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Aqua.jpg",
  "Aqua Opal": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Aqua Opal.jpg",
  "Aqua Opal Cloudy": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Aqua Opal Cloudy.jpg",
  "Aqua Opal Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Aqua Opal Iridized.jpg",
  "Aqua Opal Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Aqua Opal Satin.jpg",
  "Aqua Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Aqua Satin.jpg",
  "Autumn1": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Autumn1.jpg",
  "Autumn2": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Autumn2.jpg",
  "Azure Blue": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Azure Blue.jpg",
  "Azure Blue Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Azure Blue Satin.jpg",
  "BLACK GRAY & WHITE": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/BLACK GRAY & WHITE.jpg",
  "BLUE": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/BLUE.jpg",
  "BROWN": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/BROWN.jpg",
  "Black Amethyst First": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Black Amethyst First.jpg",
  "Black Amethyst Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Black Amethyst Satin.jpg",
  "Black Cherry": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Black Cherry.jpg",
  "Black Magic": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Black Magic.jpg",
  "Black1": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Black1.jpg",
  "Black2 Newer Version": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Black2 Newer Version.jpg",
  "Blazer": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blazer.jpg",
  "Blazer2": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blazer2.jpg",
  "Blazer3": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blazer3.jpg",
  "Blazer4": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blazer4.jpg",
  "Blazer5": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blazer5.jpg",
  "Blue Milk": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blue Milk.jpg",
  "Blue Milk2 Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blue Milk2 Satin.jpg",
  "Blue Opal": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blue Opal.jpg",
  "Blue Slag1": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blue Slag1.jpg",
  "Blue Wind Frost": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blue Wind Frost.jpg",
  "Blue Wind Frost Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Blue Wind Frost Satin.jpg",
  "Brown Banana": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Brown Banana.jpg",
  "Brown Calico": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Brown Calico.jpg",
  "Brown Calico Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Brown Calico Satin.jpg",
  "Buffett Blue": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Buffett Blue.jpg",
  "Burnt Orange": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Burnt Orange.jpg",
  "Buttercup": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Buttercup.jpg",
  "Buttercup comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Buttercup comparison.jpg",
  "Butterscotch Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Butterscotch Iridized.jpg",
  "Butterscotch Slag": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Butterscotch Slag.jpg",
  "Butterscotch Slag Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Butterscotch Slag Iridized.jpg",
  "Butterscotch Slag Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Butterscotch Slag Satin.jpg",
  "COVER PIC": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/COVER PIC.jpg",
  "Calico": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Calico.jpg",
  "Cambridge Blue Comps": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cambridge Blue Comps.jpg",
  "Cameo Bronze": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cameo Bronze.jpg",
  "Candy Corn": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Candy Corn.jpg",
  "Candy Corn Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Candy Corn Iridized.jpg",
  "Candy Corn Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Candy Corn Satin.jpg",
  "Chocolate": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Chocolate.jpg",
  "Chocolate Comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Chocolate Comparison.jpg",
  "Chocolate Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Chocolate Satin.jpg",
  "Chocolate Slag": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Chocolate Slag.jpg",
  "Clay": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Clay.jpg",
  "Cloud 9": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cloud 9.jpg",
  "Cobalt Blue New1": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cobalt Blue New1.jpg",
  "Cobalt Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cobalt Satin.jpg",
  "Cobalt&Milk": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cobalt&Milk.jpg",
  "Cobalt&MilkSatin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cobalt&MilkSatin.jpg",
  "Cobalt1": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cobalt1.jpg",
  "Cobalt2 Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cobalt2 Iridized.jpg",
  "Colonial Blue": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Colonial Blue.jpg",
  "Cranberry Comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cranberry Comparison.jpg",
  "Cranberry Ice First": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cranberry Ice First.jpg",
  "Cranberry Ice Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cranberry Ice Satin.jpg",
  "Cranberry Opal": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Cranberry Opal.jpg",
  "Crown Lilac": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crown Lilac.jpg",
  "Crown Lilac Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crown Lilac Satin.jpg",
  "Crown Tuscan Pink": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crown Tuscan Pink.jpg",
  "Crystal NEW RELEASE": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal NEW RELEASE.jpg",
  "Crystal1": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal1.jpg",
  "Crystal2 Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal2 Satin.jpg",
  "Crystal3 Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal3 Iridized.jpg",
  "Crystal32 Opal": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal32 Opal.jpg",
  "Crystal4 Opal Cloudy": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal4 Opal Cloudy.jpg",
  "Crystal5 Opal Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal5 Opal Satin.jpg",
  "Crystal6 Opal Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal6 Opal Iridized.jpg",
  "Crystal7 Opal Iridized Cloudy": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Crystal7 Opal Iridized Cloudy.jpg",
  "Custard": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Custard.jpg",
  "Custard Grape": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Custard Grape.jpg",
  "Dark Amber Final2": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Dark Amber Final2.jpg",
  "Emerald Green": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Emerald Green.jpg",
  "Emerald Green Opal": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Emerald Green Opal.jpg",
  "Emerald Green Opal Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Emerald Green Opal Satin.jpg",
  "Emerald Green Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Emerald Green Satin.jpg",
  "Emerald Green with Satin Ears": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Emerald Green with Satin Ears.jpg",
  "Fiesta": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Fiesta.jpg",
  "Fiesta Comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Fiesta Comparison.jpg",
  "Flame": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Flame.jpg",
  "Flame2": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Flame2.jpg",
  "French Vanilla": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/French Vanilla.jpg",
  "GREEN": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/GREEN.jpg",
  "Georgia Blue": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Georgia Blue.jpg",
  "Golden Lime Swirl": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Golden Lime Swirl.jpg",
  "Golden Opaline": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Golden Opaline.jpg",
  "Gray": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Gray.jpg",
  "Gray and Marble comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Gray and Marble comparison.jpg",
  "Green Banana": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Banana.jpg",
  "Green Banana Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Banana Satin.jpg",
  "Green Milk Glass": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Milk Glass.jpg",
  "Green Milk Slag": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Milk Slag.jpg",
  "Green Opal": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Opal.jpg",
  "Green Opal Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Opal Iridized.jpg",
  "Green Opal Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Opal Satin.jpg",
  "Green Slag": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Slag.jpg",
  "Green Wind Frost": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Green Wind Frost.jpg",
  "Heatherbloom": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Heatherbloom.jpg",
  "Heatherbloom Comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Heatherbloom Comparison.jpg",
  "Heirloom Pink": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Heirloom Pink.jpg",
  "Honey": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Honey.jpg",
  "Honey Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Honey Satin.jpg",
  "Hunter Green Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Hunter Green Iridized.jpg",
  "Hunter Green Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Hunter Green Satin.jpg",
  "Hunter green": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Hunter green.jpg",
  "Ice Blue IridizedFINAL": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Ice Blue IridizedFINAL.jpg",
  "Ice Lime Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Ice Lime Iridized.jpg",
  "Irish Mist": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Irish Mist.jpg",
  "Jadeite": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Jadeite.jpg",
  "Jadeite new version": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Jadeite new version.jpg",
  "Jasmine": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Jasmine.jpg",
  "Jasmine Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Jasmine Satin.jpg",
  "Jungle Moss": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Jungle Moss.jpg",
  "Kimberlite": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Kimberlite.jpg",
  "Lavender Ice": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Lavender Ice.jpg",
  "Lemon Lime Swirl": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Lemon Lime Swirl.jpg",
  "Lemon Lime Swirl Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Lemon Lime Swirl Iridized.jpg",
  "Lemon Lime Swirl Iridized Comparison": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Lemon Lime Swirl Iridized Comparison.jpg",
  "Lemon Lime Swirl Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Lemon Lime Swirl Satin.jpg",
  "Light Amber": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Light Amber.jpg",
  "Light Amber Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Light Amber Satin.jpg",
  "Light Yellow": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Light Yellow.jpg",
  "Lime": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Lime.jpg",
  "Mandarin Slag": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Mandarin Slag.jpg",
  "Mandarin Slag Satin": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Mandarin Slag Satin.jpg",
  "Marble1": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Marble1.jpg",
  "Marble2 Iridized": "https://raw.githubusercontent.com/SeadogMcGrog/mosser-cat-colors/main/Marble2 Iridized.jpg",
};